# Generated by Django 4.2.4 on 2023-09-14 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='concurrentRun',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='run.run'),
        ),
        migrations.AlterField(
            model_name='run',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
