# Generated by Django 4.2.4 on 2023-09-20 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_run_avgpace_run_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='avgPace',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='run',
            name='endTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
